### ISSUE TITLE
How to create corpus npy files from scratch

### ISSUE THREAD

**Issue by ikuyamada** [facebookresearch/NPM#3]
Hi!

I am working on your repository and have a few questions:

1. Is the code that creates the corpus npy files (e.g., `enwiki` and `new-enwiki`) available in this repository?
2. It looks like `preprocess_wiki.py` with `--save_flatten_data` outputs the similar JSON file with `input_ids`. Is it possible to create these npy files directly from this JSON file?
3. `kilt_knowledgesource.json` corresponding to `new-wiki` corpus is unavailable in this repository and the [KILT repository](https://github.com/facebookresearch/KILT). Furthermore, it seems that the preprocessing code is currently not available in the kilt repository. It is possible to get the knowledge source file anywhere?

Thank you very much in advance!

**Comment by shmsw25** [comment]
Hi!

Q1. I think the answers to Q2 and Q3 will answer to Q1.

Q2. It's not included in the repo, but let me share the code with you here. This converts the .jsonl file (i.e. output of `preprocess_wiki.py` with `--save_flatten_data`) to the .npy file.

```python
import time
import json
import numpy as np
import string
import pickle as pkl

from transformers import RobertaTokenizer

tokenizer = RobertaTokenizer.from_pretrained("roberta-large")

def convert_jsonl_to_npy(path):
    start_time = time.time()

    all_input_ids = []
    block_idx_to_token_idx = []
    valid_candidates = []
    with open(path, "r") as f:
        block_idx = 0
        for line in f:
            dp = json.loads(line)
            input_ids = dp["input_ids"][:np.sum(dp["attention_mask"])]
            tokens = [tokenizer._decode(_id) for _id in input_ids]

            valid_start, valid_end = [], []
            for idx, (token, token_id) in enumerate(zip(tokens, input_ids)):
                if token_id in [0, 2]:
                    continue

                if idx==len(tokens)-1 or tokens[idx+1].startswith(" ") or \
                        np.any([tokens[idx+1].startswith(punc) for punc in string.punctuation]):
                    valid_end.append(idx)

                if idx==0 or token.startswith(" "):
                    valid_start.append(idx)
                elif idx>0 and np.any([tokens[idx-1].endswith(punc) for punc in string.punctuation]):
                    valid_start.append(idx)
                elif token in string.punctuation and idx in valid_end:
                    valid_start.append(idx)

            valid_start = np.array(valid_start, dtype=np.uint8)
            valid_end = np.array(valid_end, dtype=np.uint8)
            valid_candidates.append([valid_start, valid_end])
            block_idx_to_token_idx.append(len(all_input_ids))
            all_input_ids += input_ids

    # save input ids
    all_input_ids = np.array(all_input_ids, dtype=np.uint16)
    np.save(path.replace(".jsonl", ".npy"), all_input_ids)
    
    # save block boundaries
    np.save(path.replace(".jsonl", "_blocks.npy"), block_idx_to_token_idx)
    
    # save valid tokens
    with open(path.replace(".jsonl", "_valid.pkl"), "wb") as f:
        pkl.dump(valid_candidates, f)
    
    print ("Finish saving %s (%dmin)" % (path, (time.time()-start_time)/60))
```

Q3. Oh, I didn't realize the script to create the KILT data is not included in the public repo. I uploaded the KILT data for `new-data` -- you can download it via `wget https://dl.fbaipublicfiles.com/NPM/kilt_knowledgesource_20220801.json`. We'll consider finding a way that allows converting public Wikipedia dump into our format.

If converting an arbitrary data to our format is needed in the future, I think the easiest is to write a script to convert it into a jsonl format based on the format of the input data (which I think is relatively easy by looking at [preprocess_wiki.py](https://github.com/facebookresearch/NPM/blob/main/preprocess/process_wiki.py) or [preprocess_cc_net.py](https://github.com/facebookresearch/NPM/blob/main/preprocess/process_cc_news.py)) and then convert it to .npy format using the script above.

**Comment by ikuyamada** [comment]
Thanks so much for your kind response! 
I think it would be very helpful for many researchers if you provide a way to construct corpus data from an arbitrary Wikipedia dump.
I close this issue since all questions have been answered.
